apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus # {"$kpt-set":"app"}
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  - configmaps
  verbs:
  - get
  - list
  - watch
