global:
  scrape_interval: 15s
  evaluation_interval: 30s
scrape_configs:
- job_name: prometheus # {"$kpt-set":"app"}
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - default # {"$kpt-set":"namespace"}
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_name]
    action: keep
    regex: prometheus # {"$kpt-set":"app"}
  - action: labelmap
    regex: __meta_kubernetes_service_label_(.+)
  - source_labels: [__meta_kubernetes_namespace]
    action: replace
    target_label: kubernetes_namespace
  - source_labels: [__meta_kubernetes_service_name]
    action: replace
    target_label: kubernetes_service_name
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - source_labels: [__meta_kubernetes_pod_name]
    action: replace
    target_label: kubernetes_pod_name
