apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- prometheus-statefulset.yaml
- prometheus-service.yaml
- prometheus-serviceaccount.yaml
images:
- name: docker.io/prom/prometheus
  newTag: v2.22.1
- name: docker.io/library/alpine
  newTag: 3.12.1
configMapGenerator:
- name: prometheus
  literals:
  - |-
    prometheus.yml=
