apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- prometheus-statefulset.yaml
- prometheus-service.yaml
- prometheus-serviceaccount.yaml
images:
- name: docker.io/prom/prometheus
  newTag: v2.22.1
configMapGenerator:
- name: prometheus-global
- name: prometheus-rule-files
- name: prometheus-scrape-configs
- name: prometheus-alerting
- name: prometheus-remote-write
- name: prometheus-remote-read
