apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
- name: prometheus-scrape-configs
  behavior: merge
  files:
  - services-with-annotations.yaml
patches:
- target:
    kind: Role
    name: prometheus
  patch: |-
    - op: add
      path: /rules/-
      value:
        apiGroups:
        - ""
        resources:
        - services
        - endpoints
        - pods
        verbs:
        - get
        - list
        - watch
- target:
    kind: ClusterRole
    name: prometheus
  patch: |-
    - op: add
      path: /rules/-
      value:
        apiGroups:
        - ""
        resources:
        - services
        - endpoints
        - pods
        verbs:
        - get
        - list
        - watch
