# The relabeling allows the actual service scrape endpoint to be configured
# for all or only some endpoints.
- job_name: 'kubernetes-service-endpoints'
  kubernetes_sd_configs:
  - role: endpoints
    # namespaces:
    #   names:
    #   - example-namespace
  relabel_configs:
  # Scrape only endpoints that have "prometheus.io/should_be_scraped = true"
  # annotation.
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_should_be_scraped]
    action: keep
    regex: true
  #
  # Customize metric path based on endpoints "prometheus.io/metric_path =
  # <metric path>" annotation.
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_metric_path]
    action: replace
    target_label: __metrics_path__
    regex: (.+)
  #
  # Scrape only single, desired port for the service based on endpoints
  # "prometheus.io/scrape_port = <port>" annotation.
  - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_scrape_port]
    action: replace
    regex: ([^:]+)(?::\d+)?;(\d+)
    replacement: $1:$2
    target_label: __address__
  #
  # Configure scrape scheme for all service scrape targets based on endpoints
  # "prometheus.io/scrape_scheme = <scheme>" annotation.
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape_scheme]
    action: replace
    target_label: __scheme__
    regex: (https?)
  #
  - action: labelmap
    regex: __meta_kubernetes_service_label_(.+)
  - source_labels: [__meta_kubernetes_namespace]
    action: replace
    target_label: kubernetes_namespace
  - source_labels: [__meta_kubernetes_service_name]
    action: replace
    target_label: kubernetes_name
